/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6795. Copyright MediaTek Inc. (C) 2013.
 * Sun May 27 17:37:05 2018
 * Do Not Modify the File.
 */

#define GPIO_DVDD_BPI     GPIO_VIO18
#define GPIO_DVDD_EXMD     GPIO_VIO18


